// Hotel API

GET localhost:7300/api/v1/hotels

###

GET localhost:7300/api/v1/hotels/6

###

POST localhost:7300/api/v1/hotels
Content-Type: application/json

{
  "hotelName": "Holiday Inn",
  "hotelAddress": "Stuttgart",
  "hotelType": "STANDARD"
}

###

PUT localhost:7300/api/v1/hotels/1
Content-Type: application/json

{
  "hotelName": "Ritz Carlton",
  "hotelAddress": "London City",
  "hotelType": "LUXURY"
}

###

DELETE localhost:7300/api/v1/hotels/2

###

// Room API

GET localhost:7300/api/v1/rooms

###

GET localhost:7300/api/v1/rooms/1

###

POST localhost:7300/api/v1/rooms/hotel/3
Content-Type: application/json

{
  "roomNumber": 11,
  "roomPrice": 1150,
  "roomType": "SINGLE"
}
